[tool.poetry]
name = "aws-lambda-sample-python"
version = "0.1.0"
description = ""
authors = ["dtorannpu <dtorannpu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
